version: 2.1
orbs:
  slack: circleci/slack@3.4.2
jobs:
  test:
    docker:
      - image: rishabhpoddar/supertokens_core_testing
      - image: mongo
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root
    resource_class: large
    steps:
      - checkout
      - run:
          name: running tests
          command: (cd .circleci/ && ./doTests.sh)
      - slack/status
workflows:
  version: 2
  tagged-build:
    jobs:
      - test:
          context:
            - slack-notification
          filters:
            tags:
              only: /dev-v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/